# --- Site settings ---
title: Jekyll Spaceship Showcase
email: 4428752+blutoniumstrom@users.noreply.github.com
description: >-
  A demonstration of the jekyll-spaceship plugin features.
# === IMPORTANT: Settings for Custom Domain ===
# If your custom domain points directly to this repository,
# the baseurl should be empty and the url should be your custom domain.
baseurl: "" # Set to "" for a root custom domain
url: "https://blutoniumstrom.com"
github_username:  blutoniumstrom

# --- Theme Settings ---
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# --- Build settings ---
plugins:
  - jekyll-feed
  - jekyll-spaceship
  - jekyll-include-cache # Required for minimal-mistakes

# Jekyll-Spaceship - All options are default values
# Note: Minimal Mistakes has its own TOC feature, but we'll use spaceship's for this demo.
spaceship:
  processors:
    - table-of-contents
    - mathjax
    - plantuml
    - mermaid
    - polyfill
    - media-embed
    - emoji
    - video-embed
  table-of-contents:
    # This layout value might need to be adjusted based on the theme's structure
    layout: 'minimal-mistakes/_layouts/default.html'
    minimum: 2
    scope: 'h2, h3'
    title: 'Table of Contents'
    folding: true
  mathjax:
    src: 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'
  plantuml:
    server: 'http://www.plantuml.com/plantuml'
